### PR TITLE
Django 1.9

### PR DESCRIPTION
**Pull request by guyguyon**
add support for Django 1.9.

### CODE REVIEW

**Comment by vijaykatam** [comment]
@guyguyon thanks for the pull request. Coverage command is failing in python 3.5 and I haven't tried to run tests in python 3 either so there might be more failures than just the coverage command. If you'd like django 1.9 support merged in soon I would suggest leaving out python 3 out for now.

**Comment by guyguyon** [comment]
@vijaykatam Coverage fails only with old Django versions, and i need it to python 3.5 and Django 1.9.
so i want to exclude those old versions from tests with Python 3.5

**Comment by guyguyon** [comment]
@vijaykatam I took your advice and removed python 3.5 from travis.yml.
Can you please check it and merge it?

**Comment by vijaykatam** [comment]
:+1: looks good

**Pull request merged**
